export PATH=$HOME/.local/bin:/var/lib/flatpak/exports/bin:$PATH
export ZSH="$HOME/.oh-my-zsh"
export LANG=en_US.UTF-8
export ARCHFLAGS="-arch x86_64"

HISTFILE=~/.bash_history
ZSH_THEME="refined"
COMPLETION_WAITING_DOTS="true"

zstyle ':omz:update' mode disabled  # disable automatic updates
zstyle ':omz:update' frequency 14

setopt autocd

plugins=(
  git 
  sudo 
  web-search 
  zsh-autosuggestions
)
source $ZSH/oh-my-zsh.sh

ZSH_WEB_SEARCH_ENGINES=(
  brave "https://search.brave.com/search?q="
)
alias brv="web_search brave"

alias vim="nvim"
alias q="exit"

chpwd() ls
